// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPCDtgN2HzsOjHFtStlJfXkHFXIMvrCs',
    appId: '1:1012140304801:web:dd2b6d961dc1516f8383e0',
    messagingSenderId: '1012140304801',
    projectId: 'vitalxcare',
    authDomain: 'vitalxcare.firebaseapp.com',
    databaseURL: 'https://vitalxcare-default-rtdb.firebaseio.com',
    storageBucket: 'vitalxcare.appspot.com',
    measurementId: 'G-CZKJX6FH4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DOz9Cn9Sow1cRQ3LUPvt4-AtNUya7WI',
    appId: '1:1012140304801:android:a5c71e04a8f5f87d8383e0',
    messagingSenderId: '1012140304801',
    projectId: 'vitalxcare',
    databaseURL: 'https://vitalxcare-default-rtdb.firebaseio.com',
    storageBucket: 'vitalxcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6h4lHL9kobaymHRW1rs_FRmDZ7yaoAi8',
    appId: '1:1012140304801:ios:cc188b35588d41498383e0',
    messagingSenderId: '1012140304801',
    projectId: 'vitalxcare',
    databaseURL: 'https://vitalxcare-default-rtdb.firebaseio.com',
    storageBucket: 'vitalxcare.appspot.com',
    iosClientId: '1012140304801-hdp05f7i2r4u5dhagjcaojecdvid4g1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalxcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6h4lHL9kobaymHRW1rs_FRmDZ7yaoAi8',
    appId: '1:1012140304801:ios:cc188b35588d41498383e0',
    messagingSenderId: '1012140304801',
    projectId: 'vitalxcare',
    databaseURL: 'https://vitalxcare-default-rtdb.firebaseio.com',
    storageBucket: 'vitalxcare.appspot.com',
    iosClientId: '1012140304801-hdp05f7i2r4u5dhagjcaojecdvid4g1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalxcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPCDtgN2HzsOjHFtStlJfXkHFXIMvrCs',
    appId: '1:1012140304801:web:08c0e594a488ea878383e0',
    messagingSenderId: '1012140304801',
    projectId: 'vitalxcare',
    authDomain: 'vitalxcare.firebaseapp.com',
    databaseURL: 'https://vitalxcare-default-rtdb.firebaseio.com',
    storageBucket: 'vitalxcare.appspot.com',
    measurementId: 'G-7XG0SLPW15',
  );

}